name: Build Windows

on:
    pull_request:
        branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        git checkout 2023.05
        .\bootstrap-vcpkg.bat

    - name: Install GTK+ 3.0
      run: |
        .\vcpkg\vcpkg integrate install
        .\vcpkg\vcpkg install gtk:x64-windows

    - name: Checkout emerald repo
      uses: actions/checkout@v3
      with:
        repository: MaksymT17/emerald
        ref: ${{ github.head_ref }}
        path: emerald

    - name: Build artifacts with Cmake
      run: |
        cd emerald &&
        echo "removing existing build folder..."
        mkdir build &&
        echo "preparing new build with cmake..." &&
        cd build/ &&
        cmake .. &&
        make &&
        echo "Build complete!"
      shell: bash