name: Build Windows

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install pkg-config
      run: |
        choco install pkgconfiglite
        choco install gtk-runtime

    - name: Checkout emerald repo
      uses: actions/checkout@v3
      with:
        repository: MaksymT17/emerald
        ref: ${{ github.head_ref }}
        path: emerald

    - name: Build artifacts with CMake
      run: |
        cd emerald &&
        echo "removing existing build folder..."
        mkdir build &&
        echo "preparing new build with cmake..." &&
        cd build/ &&
        cmake .. &&
        cmake --build . &&
        echo "Build complete!"
      shell: bash